python3 datasets/build_pools.py \
  --task can \
  --dp-rollouts-root scratch_dir/logs/robomimic__square/overnight_full_square_demos50/seed0/dp_rollouts \
  --num-expert-trajs 50 \
  --train-size 240 \
  --eval-size 80 \
  --sample-size 300 \
  --train-expert-frac 0.6 \
  --train-late-frac 0.3 \
  --train-rest-frac 0.1 \
  --sample-early-frac 0.8 \
  --sample-rest-frac 0.2 \
  --output-dir scratch_dir/logs/robomimic__square/overnight_full_square_demos50/seed0/pools_v1
